-- All runtime state, organized into domain sub-tables.
-- Defaults sourced directly from DeclareOuters pre/main/post/global in kissassist.mac.
-- No logic here — pure data. Every other module imports this and reads/writes State fields.
-- Cross-module communication happens through State exclusively (star topology, no circular deps).

local State = {
    terminate = false,  -- main loop exit flag

    session = {
        role            = 'assist',
        assistAt        = 95,
        mainAssist      = '',
        mainAssistClass = '',
        mainAssistType  = '',
        originalRole    = '',
        iAmABard        = false,  -- set at startup from Me.Class
        iAmMA           = false,
        iAmDead         = false,
        zoneName        = '',
        iniFileName     = '',
        iniSet          = false,
        buffFileName    = 'KissAssist_Buffs.ini',
        infoFileName    = 'KissAssist_Info.ini',
        kissRevision    = '039',
        macroVer        = '1.0.0',
        macroName       = 'KissAssist',
        kissAssistVer   = '',
        loadFromIni     = false,
        forceAlias      = true,
        broadcastSay    = 'bc',
        bindActive      = false,
        mercInGroup     = false,
        mercAssisting   = false,
        chaseAssist     = false,
        pullPath        = 'null',
        parseDPSTimer   = 0,
    },

    debug = {
        general   = false,
        all       = false,
        buffs     = false,
        cast      = false,
        chainpull = false,
        combat    = false,
        heals     = false,
        logging   = false,
        mez       = false,
        move      = false,
        pet       = false,
        pull      = false,
        rk        = false,
        time      = false,
    },

    combat = {
        aggroTargetID      = '',
        aggroTargetID2     = '0',
        attacking          = false,
        burnActive         = false,
        burnCalled         = false,
        burnOn             = true,
        burnID             = 0,
        calledTargetID     = 0,
        combatStart        = false,
        eventByPass        = false,
        eventFlag          = false,
        gotHitToggle       = false,
        lastCalledTargetID = 0,
        lastTargetID       = 0,
        missingComponent   = false,
        mobCount           = 0,
        mobFlag            = true,
        myTargetID         = 0,
        myTargetName       = '0',
        namedCheck         = false,
        raidAssistEntry    = 1,
        raidTargetID       = '0',
        validTarget        = false,
        xSlotTotal         = 20,
        xTSlot             = 0,
        xTSlot2            = 0,
        xTarAutoSet        = true,
    },

    cast = {
        status           = 'IDLE',  -- IDLE/CASTING/SUCCESS/FIZZLE/INTERRUPT/RESIST/TIMEOUT
        castReturn       = 'CAST_CANCELLED',
        castResult       = '',
        castCheck        = '',
        checkResisted    = false,
        failCounter      = 0,
        failMax          = 3,
        gemSlots         = 8,
        miscGem          = 0,
        miscGemLW        = 0,
        iamCastingID     = 0,
        lastResisted     = false,
        reMemCast        = false,
        reMemCastLW      = false,
        reMemWaitLong    = 'null',
        reMemWaitShort   = 'null',
        reMemMiscSpell   = '',  -- set post-ini: Me.Gem[miscGem].Name
        reMemMiscSpellLW = '',  -- set post-ini: Me.Gem[miscGemLW].Name
        spellReadyL      = false,
    },

    pull = {
        aggroTargetID  = '',
        ammo           = 'NULL',
        beginMobID     = '',
        chainPullTemp  = '',
        chainPull      = false,
        heading        = 0.0,
        hold           = false,
        holdCond       = '0',
        ignore1        = 'NULL',
        ignore2        = 'NULL',
        ignore3        = 'NULL',
        item           = 'NULL',
        lastMobPullID  = 0,
        lSide          = 0.0,
        rSide          = 0.0,
        max            = 0,
        maxCount       = 500,
        min            = 0,
        mob            = 0,
        mobsToPullFirst = 'all',
        mobsToPullRaw  = 'null',
        mobsToIgnoreByID = 'null',
        moveUse        = '',
        navDistance    = 0,
        pathWpCount    = 0,
        pulled         = false,
        pulling        = false,
        range          = 0,
        ranking        = 0,
        searchIter     = 1,
        tempMaxRadius  = 0,
        tooFar         = false,
        waitRemaining  = 0,
        waypointZRange = 0,  -- set post-ini: mirrors MaxZRange
        withAlt        = 'Melee',
        xpCheck        = true,
    },

    movement = {
        advpathPoint    = 0,
        advpathX        = 0.0,
        advpathY        = 0.0,
        advpathZ        = 0.0,
        campX           = 0,
        campY           = 0,
        campZ           = 0,
        campZone        = 0,
        cantHit         = false,
        cantSee         = false,
        chaseOnValue    = 1,
        checkOnReturn   = false,
        dontMoveMe      = false,
        dStickHow       = '0',
        locDelayCheckUW = false,
        lookForward     = 0,
        navPathHelper   = true,
        rememberCamp    = false,
        returnToCamp    = false,
        stayPut         = false,
        stickDist       = 13,
        stickDistUW     = 10,
        toClose         = false,
        whoToChase      = '',
        zDist           = 0.0,
    },

    heal = {
        autoRezAll          = false,
        corpseRezCheck      = 'null',
        groupWatchPct       = 20,
        healAgain           = false,
        healRemChk1         = 'Divine Barrier',
        healRemChk2         = 'Touch of the Divine',
        healRemChk3         = 'null',
        medding             = false,
        meddingInterrupted  = false,
        medStat             = '',
        medStat2            = 'Endurance',
        needCuring          = false,
        sHealPct            = 0,
        singleHealPoint     = false,
        singleHealPointMA   = false,
        singleHealPointRange = false,
    },

    buffs = {
        blockedCount      = 0,
        durationMod       = 1.0,
        extendedList      = '',
        forceBuffs        = false,
        globalExtendedList = '',
        hasBuffDuration   = false,
        kaBegActive       = false,
        kaBegForList      = '',
        kaPetBegActive    = false,
        kaBegForPetList   = '',
    },

    pet = {
        activeState   = false,
        attackRange   = 0,
        focusOn       = false,
        globalToysGave = '',
        suspendState  = false,
        tanking       = false,
        targetSwitch  = false,
        totCount      = 0,
        toyList       = '',
    },

    mez = {
        broke      = false,
        debuffCount = 0,
        immuneIDs  = '',
        aeCount    = 0,
        mobCount   = 0,
        mobDone    = false,
        mobFlag    = false,
    },

    bard = {
        dpsTwisting    = false,
        gomActive      = false,
        gomByPass      = false,
        startTwist     = false,
        twisting       = false,
        twistHold      = false,
        wasTwisting    = 'null',
        wasTwistingBool = false,
    },

    loot = {
        bagNum        = 0,
        bagNumLast    = 0,
        cursorID      = 0,
        cursorIDCount = 0,
        dragCorpse    = false,
        looterAssigned = false,
    },

    dps = {
        lastCast   = '',
        parseTimer = 0,
        paused     = false,
        spam       = false,
        target     = 0,
        writeOn    = false,
    },

    -- All .mac timer variables stored as os.clock() expiry timestamps; 0 = expired/unset.
    timers = {
        addSpam        = 0,
        aggroOff       = 0,
        campOnDeath    = 0,
        campfire       = 0,
        campfireClick  = 0,
        cleanBuffs     = 0,
        cursorID       = 0,
        debugTicker    = 0,
        engageWait     = 0,
        eventTimer     = 0,
        gomTimer       = 0,
        iniNext        = 0,
        joinedParty    = 0,
        justZoned      = 0,
        lastHealCheck  = 0,
        maSit          = 0,
        mezAE          = 0,
        petAttack      = 0,
        petBuffCheck   = 0,
        petFollow      = 60,  -- .mac default: 60s
        pullAlert      = 0,
        pullTimer      = 0,
        pullWait1      = 0,
        pullWait2      = 0,
        readBuffs      = 0,
        sitToMed       = 0,   -- .mac default: 6s, set at runtime
        spam           = 0,
        spam1          = 0,
        spam2          = 0,
        spam3          = 0,
        tank           = 0,
        tribute        = 0,
        waitTimer      = 0,
        writeBuffs     = 0,
        writeBuffsMerc = 0,
        writeBuffsPet  = 0,
    },

    misc = {
        aeDisplayMobInfo     = false,
        ammoSwitch           = false,
        banestrike           = '',
        colorIdx             = 0,
        colorList            = 'tWgtuwyr',
        conColor             = 't',
        dmz                  = false,  -- set at runtime: Zone.ID in {345,344,202,203,279,151,33506}
        dnOut                = 'null',
        globalIndex          = 0,
        itemsGiven           = 0,
        lastZone             = 0,
        macroReturn          = '',
        mapSet               = false,
        mountOn              = true,
        mq2castReload        = false,
        mq2meleeReload       = false,
        mq2spawnMasterReload = false,
        myAAExp              = 0.0,
        myExp                = 0.0,
        myMerc               = '0',
        origRanged           = '',
        rangedSwitch         = false,
        redguides            = true,
        searchType           = '',
        tempAmmo             = '',
        winTitleText         = 'null',
    },

    arrays = {
        beforeArray  = {'null','null','null','null','null'},
        mashArray    = {'null','null','null','null','null','null','null','null','null','null'},
        weaveArray   = {},  -- [50]  string, 'null'
        mezArray     = {},  -- [50][3] string, 'NULL'
        xTarToHeal   = {},  -- [20]  int, 0
        pullPathX    = {},  -- [999] float, 0.0
        pullPathY    = {},
        pullPathZ    = {},
    },
}

-- Initialize variable-length arrays to their .mac defaults.
for i = 1, 50  do State.arrays.weaveArray[i] = 'null' end
for i = 1, 50  do State.arrays.mezArray[i]   = {'NULL','NULL','NULL'} end
for i = 1, 20  do State.arrays.xTarToHeal[i] = 0 end
for i = 1, 999 do
    State.arrays.pullPathX[i] = 0.0
    State.arrays.pullPathY[i] = 0.0
    State.arrays.pullPathZ[i] = 0.0
end

return State
